### ISSUE TITLE
🤖sweet irony...error code 32 for README code

### ISSUE THREAD

**Issue by batpigandme** [mkearney/botornot#1]
It's probably because I'm ~50% robot…or it could be the Twitter API— I'm not sure. 🤔

Do I need token to play 😭?

``` r
## load package
library(botornot)

## select users
users <- c("realdonaldtrump", "netflix_bot",
           "kearneymw", "dataandme", "hadleywickham",
           "ma_salmon", "juliasilge", "tidyversetweets")

## get botornot estimates
data <- botornot(users)
#> Error code: 32
#> Could not authenticate you.
#> Error in if (tub == "tweets") {: argument is of length zero
```

Created on 2018-02-16 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by mkearney** [comment]
This is probably due to a known issue with rtweet. See: https://github.com/mkearney/rtweet/issues/179#issuecomment-365689068. I'm still waiting to hear back from Twitter...

Also, the pkg has been updated with a better algorithm. @batpigandme is human once again! See the README for updates estimates.

**Comment by batpigandme** [comment]
Well, now that I'm a human, consider the issue closed! Really I just felt like having an existential crisis in the repo.
