### ISSUE TITLE
is this a real package?

### ISSUE THREAD

**Issue by randomgambit** [mkearney/botornot#3]
hello, 

I just wonder: is this a real package? Like juliasilge with a 50% bot probability seems a pretty bad prediction right? Am I missing something?

Thanks!

**Comment by mkearney** [comment]
It is! But it's in early development. 

The original model was trained on real data and performed well on test data. But the features were limited to user-level data (not tweet-level). I've made several changes since, and the current README estimates come from a model I was in the middle of troubleshooting. I'll try to get this on CRAN in the next couple of weeks. And when that happens, the package will be a lot more stable.
