### ISSUE TITLE
Unauthorized Error

### ISSUE THREAD

**Issue by kmkmjohnson** [mkearney/botornot#7]
Thanks for writing this. I tried your sample code and got the following error:
```
Error in init_oauth1.0(self$endpoint, self$app, permission = self$params$permission,  : 
  Unauthorized (HTTP 401).
```
Any insight into this? 
Thanks!

**Comment by selopab** [comment]
Before using the function you have to declare your Twitter API credentials. Check out this page for further instructions: 
http://thinktostart.com/twitter-authentification-with-r/

Worked perfectly for me.

**Comment by mkearney** [comment]
Yeah, this inconvenience was due to a recent action taken by Twitter. There's documentation for setting up your access token and saving it as an environment variable (like @selopab's link, which looks good to me).

## rtweet vignette 
Step by step instructions on creating and saving Twitter token: http://rtweet.info/articles/auth.html

## R: Collecting and analyzing Twitter data slides
Some recent slides I used, which includes step by step instructions on creating and saving Twitter token: https://mkearney.github.io/nicar_tworkshop/

**Comment by kmkmjohnson** [comment]
Worked great. Thanks!
